SELECT AVG(RENTAL_RATE) FROM FILM

SELECT COUNT(*) FROM FILM WHERE TITLE LIKE 'C%'

SELECT MAX(LENGTH) FROM FILM WHERE RENTAL_RATE = 0.99

SELECT COUNT(DISTINCT REPLACEMENT_COST) FROM FILM WHERE LENGTH > 150