SELECT RATING FROM FILM GROUP BY RATING

SELECT REPLACEMENT_COST,COUNT(*)  FROM FILM GROUP BY REPLACEMENT_COST HAVING COUNT(*) > 50 ORDER BY REPLACEMENT_COST ASC

SELECT  STORE_ID , COUNT(*) "CUSTOMER_CNT"  FROM CUSTOMER GROUP BY STORE_ID

SELECT COUNTRY_ID, COUNT(*) FROM CITY GROUP BY COUNTRY_ID ORDER BY COUNT(*) DESC LIMIT 1