SELECT LENGTH(title),* FROM film WHERE title LIKE '%n' ORDER BY (LENGTH(title)) DESC LIMIT 5

SELECT LENGTH(title),* FROM film WHERE title LIKE '%n' ORDER BY (LENGTH(title)) ASC  OFFSET 5 LIMIT 5

SELECT * FROM CUSTOMER WHERE store_id = 1  ORDER BY (last_name) DESC LIMIT 4